load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "dns_representation",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.hpp",
    ]),
    visibility = ["//visibility:public"],
)
